// Generated by Wrangler by running `wrangler types --experimental-include-runtime=./runtime.d.ts`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
export interface Env {
	LAT: string;
	LON: string;
	'46_ELKS_AUTH': string;
	PHONE_NUMBER_RECEIVER: string;
}
